### ISSUE TITLE
Move away from lodash dot packages

### ISSUE THREAD

**Issue by steelbrain** [minseoksuh/eslint-plugin-consistent-default-export-name#9]
Hi @minseoksuh!

Thank you for writing this package! I noticed that you were using lodash dot packages, ie. [lodash.camelcase](https://www.npmjs.com/package/lodash.camelcase). These packages are no longer maintained (cannot find source right now) (last update to this package was 6 years ago).

I would request that you use the main lodash package (https://www.npmjs.com/package/lodash) and then import it like `import camelcase from 'lodash/camelcase'`

Thanks!

**Comment by minseoksuh** [comment]
I originally decided to do this because of PR.

But as you said. 
https://lodash.com/per-method-packages

suggests I dont do this.
Thanks! I will make this change.

**Comment by minseoksuh** [comment]
Processed in v0.0.15.
Thanks again for the input!

**Comment by jaydenseric** [comment]
@minseoksuh something is wrong with the files that are committed in this repo; v0.0.15 is published to npm but only v0.0.14 files are committed in this repo:

https://github.com/minseoksuh/eslint-plugin-consistent-default-export-name/blob/be15da14cc9d53a9bf6d3ab58b6d1183b94e2781/package.json#L3

Perhaps you forgot to push up your local changes?

**Comment by tylerlaprade** [comment]
@minseoksuh, what's the status here?
